[menu]
title = "General Ticket Information"
description = """
Content creation info -
> This section is to be used only when applying for our creator roles. Before applying ensure that you meet our requirements. The requirements are as follows:
> - @Verified Artists ─ Well known artists within the community, must have 10k monthly listeners on Spotify.
> - @Content Creators ─ You're a Youtuber or a Streamer, you're allowed this role if you have 250 views on majority of your videos and 1000 subs on YouTube or 1000 followers on Twitch.
> - @Musicians ─ Have three or more songs uploaded on a public platform and show active motivation towards making more in the future.
> - @Producers ─ Have one or more beats uploaded on a public platform and show active motivation towards making more in the future.
"""