[levels]
title = "Claim your level roles"
category = "1169287372349902978"

[reports]
title = "Report a member"
category = "1169287372349902978"

[roles]
title = "Get a content creator role"
description = "Receive musician / producer / content creator roles"
category = "1169287372349902978"